requirements.txt: Relax versioning by switching from '==' to '~='
This change should make it easier to use patchscope in other project
without encountering problems with conflicting dependencies, like
in the following example:

 ERROR: Cannot install -r requirements.txt (line 103) and PyYAML==6.0.3
 because these package versions have conflicting dependencies.

 The conflict is caused by:
    The user requested PyYAML==6.0.3
    patchscope 0.6.3 depends on pyyaml==6.0.2

The pyproject.toml project file already used '~=' for versioning
dependencies.