languages.py: Ensure that EXT_TO_LANGUAGES takes precedence
Before this change what was read from GitHub Linguist's 'languages.yml'
https://github.com/github-linguist/linguist/blob/master/lib/linguist/languages.yml
into .ext_primary and .ext_lang took precedence over what is in
EXT_TO_LANGUAGES.  This was not correct, as user choices provided
with --ext-to-language option should override defaults.

This also fixes the bug detected by tests/test_languages.py test
that with newest 'language.yml' the *.md extension was assigned not
to Markdown file format, but to GCC Machine Description file format
(that just so happens to be before Markdown in alphabetical order).

```
=========================== short test summary info ============================
FAILED tests/test_languages.py::test_Languages - AssertionError: for 'README.md' file
assert {'language': ...'programming'} == {'language': ...ype': 'prose'}

  Differing items:
  {'language': 'GCC Machine Description'} != {'language': 'Markdown'}
  {'purpose': 'programming'} != {'purpose': 'documentation'}
  {'type': 'programming'} != {'type': 'prose'}

  Full diff:
    {
  -     'language': 'Markdown',
  -     'purpose': 'documentation',
  +     'language': 'GCC Machine Description',
  +     'purpose': 'programming',
  -     'type': 'prose',
  ?                 ^^
  +     'type': 'programming',
  ?                 ^^^^^^^^
    }
```

The Languages class issued a warning, but that is easily missed:
"Extension collision in ext_lang for 'README.md': ['GCC Machine Description', 'Markdown']"

(cherry picked from commit 91d9e5e3a2ec56f892d756c50a9f8e654f5f4ab3)