utils.git: Cache batch_command property of GitRepo manually
Switch from using @functools.cached_property to jus @property
for the GitRepo.batch_command, and creating new persistent subprocess
connecting to `git cat-file --batch-command` if self._cat_file is None.

This changes the behavior of batch_command to re-start `git cat-file`
after call to .close_batch_command().  Thanks to this, you can call
.are_valid_objects() and .filter_valid_commits() methods of GitRepo,
and they would not fail after call to .close_batch_command().

Without this change, some tests in test_utils_git.py fail because
example_repo is module-scoped fixture, with

  =========================== short test summary info ============================
  FAILED tests/test_utils_git.py::test_are_valid_objects - ValueError: I/O operation on closed file.
  FAILED tests/test_utils_git.py::test_filter_valid_commits - ValueError: I/O operation on closed file.
  =================== 2 failed, 80 passed, 8 skipped in 9.64s ====================