languages.py: Fix bug in Languages._path2lang
The languages_exceptions() function was passed language found so far,
but taking into account only self.filenames_lang from 'languages.yml',
and it did not take into account FILENAME_TO_LANGUAGES global variable
with override.

Therefore, for example for 'ChangeLog' file, the result would be empty
list of possible languages, even though if we got to this place we know
that we have detected at least one language.

Fixes the following error (caught and printed):

    File "python-diff-annotator/src/diffannotator/annotate.py", line 541, in __init__
      source_meta_dict = LANGUAGES.annotate(self.source_file)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "python-diff-annotator/src/diffannotator/languages.py", line 297, in annotate
      language = self._path2lang(path)
                 ^^^^^^^^^^^^^^^^^^^^^
    File "python-diff-annotator/src/diffannotator/languages.py", line 230, in _path2lang
      return ret[0]
             ~~~^^^
  IndexError: list index out of range

Test added to catch any regressions.  While at it, omprove detection of
strange cases in 'tests/test_language.py'.