test_cli.py: Add test_annotate_then_gather_data_sizes_and_spreads()
This test uses changes in commit 87de301db14745ab920d7e32b53d926236a4f2af
from the tensorflow/tensorflow repository as a diff to annotate.  It
tests diff-gather-stats (gather_app) with `--annotations-dir=`, which
was not tested previously.

.
NOTE that running all test might fail at this test because of the bad
interaction between tests, but running this test alone passes.

  Traceback (most recent call last):
    File "python-diff-annotator\src\diffannotator\annotate.py", line 488, in process
      patch_annotations['changes'].update(annotated_patch_file.process())
      hunk_data = AnnotatedHunk(self, hunk).process()
    File "python-diff-annotator\src\diffannotator\annotate.py", line 1267, in process
      line_annotation = AnnotatedPatchedFile.line_callback(line_tokens)
    File "<string>", line 2, in detect_all_whitespace_line
  IndexError: list index out of range

The code of detect_all_whitespace_line() can be found in
tests/test_code_fragments/example_line_callback_func.py