panel/02-contributors_graph.py: Attempt adding plots to authors grid
Group then resample was tested to work correctly, as was extracting
the DataFrame for a single author to plot.

Unfortunately, due to some very strange error I was not able to add
per-author plot to each Card of the authors grid.  Using <widget>.value,
wrapping with pn.rx(), wrappig with pn.rx() and pn.ReactiveExpr() - none
worked, failing with the following error:

  holoviews.core.data.interface.DataError:
    Having a non-string as a column name in a DataFrame is not supported.

When checking type of the `column` parameter, its type() is <class 'str'>,
so I have no idea WTF is happening.  I need to ask on HoloViz's Discourse
or even send a bug report of this issue.

Therefore currently every Card displays the same plot - which has linked
zoom on start, then if for example "top N" is changed it gets unlinked
with non-fatal errors:
  ERROR: panel.reactive - Callback failed for object named
     "autoscale 'y' axis when using zoom tools" changing property {'value': False}
  TypeError: link_axes() takes 2 positional arguments but 4 were given
  numpy.exceptions.DTypePromotionError: The DType <class 'numpy.dtypes.DateTime64DType'>
     could not be promoted by <class 'numpy.dtypes._PyFloatDType'>. This means
     that no common DType exists for the given inputs. For example they cannot
     be stored in a single array unless the dtype is `object`. The full list of DTypes is:
     (<class 'numpy.dtypes.DateTime64DType'>, <class 'numpy.dtypes._PyFloatDType'>)

Also, without providing `height` value, the per-author plots get squished
vertically, even if one provides `aspect_ratio` parameter.

TODO: try partial binding with pn.bind(), search for "partial" in the
https://param.holoviz.org/user_guide/Reactive_Expressions.html