gather_data.py: Fix issue with size metrics mixed with file changes
Currently not only 'commit_metadata', but also all patch sizes and
patch spreads metrics (like 'n_files') are intermingled with the
information about anotations for changed files.  Ensure that this
info, like 'commit_metadata', is not mistaken for file changes info.

This fixes the following error caught by tests/test_cli.py test:

  E       AssertionError: gather app runs 'purpose-counter' subcommand on generated annotations without errors
  E       assert 1 == 0
  E        +  where 1 = <Result TypeError("argument of type 'int' is not iterable")>.exit_code

  tests\test_cli.py:530: AssertionError

This, in turn, was caused by the following exception (this find was
helped with changes introduced in the previous commit):

  Exception: argument of type 'int' is not iterable
  Traceback:
  [...]
    File "python-diff-annotator\src\diffannotator\gather_data.py", line 139, in create
      if 'purpose' not in data[change_file] and change_file == 'commit_metadata':

NOTE that only one of those places was detected by test_cli.py tests;
other call sites were added to match what needed to be fixed.