panel/01-timeline.ipynb: Switch from pn.bind to pn.rx (BUGGY!)
The Panel documentation recomments using reactive components instead
of bounding functions, especially instead of binding to bound functions.
The latter can help you to quickly explore your data, but it can be
(and is) inefficient as the results are calculated from scratch for each
call.

Another solution would be to use pn.cache, perhaps limited to session
for the ease of development.  However, some places used pn.rx for
convenience already in addition to using pn.bind.

This commit switches from using pn.bind, to using pn.rx for all plots.

https://panel.holoviz.org/tutorials/basic/pn_bind.html
https://panel.holoviz.org/tutorials/basic/pn_rx.html
https://panel.holoviz.org/tutorials/intermediate/parameters.html
https://param.holoviz.org/user_guide/Reactive_Expressions.html

.
UNFORTUNATELY, it turned out that some change in this commit made
Panel so confused, that `panel serve` and 'Preview with Panel' return
500: Internal Server Error, with the following error message:

  2024-10-24 23:02:08,643 Uncaught exception GET /01-timeline (172.18.65.210)
  HTTPServerRequest(protocol='http', host='158.75.112.151:5007', method='GET', uri='/01-timeline', version='HTTP/1.1', remote_ip='172.18.65.210')
  Traceback (most recent call last):
    File "~/.venv/lib/python3.12/site-packages/tornado/web.py", line 1790, in _execute
      result = await result
               ^^^^^^^^^^^^
    File "~/.venv/lib/python3.12/site-packages/panel/io/server.py", line 466, in get
      session = await self.get_session()
                ^^^^^^^^^^^^^^^^^^^^^^^^
    File "~/.venv/lib/python3.12/site-packages/panel/io/server.py", line 356, in get_session
      session = await super().get_session()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "~/.venv/lib/python3.12/site-packages/bokeh/server/views/session_handler.py", line 145, in get_session
      session = await self.application_context.create_session_if_needed(session_id, self.request, token)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "~/.venv/lib/python3.12/site-packages/bokeh/server/contexts.py", line 240, in create_session_if_needed
      self._application.initialize_document(doc)
    File "~/.venv/lib/python3.12/site-packages/panel/io/application.py", line 149, in initialize_document
      super().initialize_document(doc)
    File "~/.venv/lib/python3.12/site-packages/bokeh/application/application.py", line 190, in initialize_document
      h.modify_document(doc)
    File "~/.venv/lib/python3.12/site-packages/panel/io/handlers.py", line 668, in modify_document
      nodes = ast.parse(source, os.fspath(path))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/lib/python3.12/ast.py", line 52, in parse
      return compile(source, filename, mode, flags,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "~/notebooks/panel/01-timeline.ipynb", line 1702
      "tags": []
                ^
  SyntaxError: '(' was never closed

Hovewer, when examining the 01-timeline.ipynb contents, line 1702 is in the middle
of cell metadata, with generated HTML.  Why is `panel serve` trying to parse it as Python
code?

   1688   {
   1689    "cell_type": "code",
   1690    "execution_count": 11,
   1691    "id": "93692ac2-f5f1-4e76-9dd4-8ff151f5bd21",
   1692    "metadata": {
   1693     "panel-layout": {
   1694      "height": 135290,
   1695      "visible": true,
   1696      "width": 100
   1697     }
   1698    },
   1699    "outputs": [
   1700     {
   1701      "data": {
** 1702       "text/html": [
   1703        "<div>\n",
   1704        "<style scoped>\n",
   1705        "    .dataframe tbody tr th:only-of-type {\n",
   1706        "        vertical-align: middle;\n",
   1707        "    }\n",
   1708        "\n",

What's strange is that JupyterLab does not show any errors, and the template
tha is being marked as .servable() for Panel displays just right inside
Jupyter notebook interface.

Solving this &*%@! issue would require trying to re-add changes from this
commit step by step, each time checking if there are no problems rendering
the 01-timeline.ipynb Jupyter notebook as the `panel` app.

Problem might be related to the following question (TODO: make bug report):
https://discourse.holoviz.org/t/panel-1-4-runtime-error-but-not-in-notebook/7078
https://discourse.holoviz.org/t/problems-running-notebook-from-reference-panes-matplotlib-html-in-panel-strange-syntaxerror/8334