utils.git: Add `single_use` param to .are_valid_objects() and .filter_valid_commits()
This is meant to help the problem of

  OSError: [Errno 24] Too many open files

in the common case when e.g. .filter_valid_commits() is used once
per GitRepo.