annotate.py: Fix bug for 'Binary files ... differ' patches
When there is change to a binary file, Git will show this using the
"Binary files a/foo and b/foo differ" message in place of diff;
therefore for unidiff there are 0 hunks.  Make the
compute_sizes_and_spreads() method of AnnotatedPatchedFile class
handle this case correctly.

Additionally, you can now find number of changed "binary" files with
'n_binary_files' field in the compute_sizes_and_spreads() method output.

.
Witout this fix, you would get the following error (caught and
printed):

  File "python-diff-annotator/src/diffannotator/annotate.py", line 786, in compute_sizes_and_spreads
    (self.patched_file[-1].source_start + self.patched_file[-1].source_length - 1
     ~~~~~~~~~~~~~~~~~^^^^
  IndexError: list index out of range

Add test for this specific issue.