utils.git: Do not fail on invalid utf-8, use errors='backslashreplace'
To avoid raising exceptions caused by byte sequences in Git command
output that are invalid utf-8, for example

  UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 4922: invalid start byte

try to handle those errors more grcefully (they may happen in diffs).

Use the `errors` parameter to subprocess.Popen() or subprocess.run()
(passed down to `io.TextIOWrapper`), which is an optional parameter
that specifies how encoding and decoding errors are to be handled.
- 'strict' to raise a ValueError exception if there is an encoding error
  (the default of None has the same effect),
- 'ignore' to ignore errors (which can lead to data loss)
- 'replace' causes a replacement marker (such as '?') to be inserted
  where there is malformed data.
- 'backslashreplace' causes malformed data to be replaced by a backslashed
  escape sequence.
- 'surrogateescape' will represent any incorrect bytes as low surrogate code
  units ranging from U+DC80 to U+DCFF. These surrogate code units will then
  be turned back into the same bytes when the 'surrogateescape' error handler
  is used when writing data. This is useful for processing files in an unknown
  encoding.

Examples:

    >>> b'\xff'.decode(encoding='utf-8', errors='ignore')
    ''
    >>> b'\xff'.decode(encoding='utf-8', errors='replace')
    '�'
    >>> b'\xff'.decode(encoding='utf-8', errors='backslashreplace')
    '\\xff'
    >>> b'\0xff'.decode(encoding='utf-8', errors='surrogateescape')
    '\x00xff'

The default now is 'backslashreplace'.

While at it, fold overly long lines in the area.