Rename and improve purpose_to_annotation_callback()
Without the fix running the annotate.py script without providing
the --purpose-to-annotation global option made the script crash
with
  TypeError: object of type 'NoneType' has no len()

Perhaps it could be fixed by moving from List[str] to
Optional[List[str]] as the type of purpose_to_annotation argument.